# 配置端口
server:
  port: 8764
  servlet:
    context-path: /boot

# 配置数据源及Redis
spring:
  # 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cache:
    type: redis # 指定缓存类型
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_shiro?useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    timeout: 6000
    password: jydadmin123
    jedis:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10    # 连接池中的最大空闲连接数
        min-idle: 5     # 连接池中的最小空闲连接数
  devtools:
    restart:
      enabled: true # 设置开启热部署
      additional-paths: src/main/java # 重启目录

# Mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或分号隔开（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值，可以不配置
  global-config:
    db-config:
      # 主键类型： AUTO：“数据库ID自增”，INPUT：“用户输入ID”，ID_WORKER：“全局唯一ID（数字类型唯一ID）”，UUID：“全局唯一ID UUID”
      id-type: auto
      # 字段策略：IGNORED：“忽略判断”，NOT_NULL：“非 NULL 判断”，NOT_EMPTY：“非空判断”
      field-strategy: not_empty
      # 数据库类型
      db-type: mysql
  configuration:
    # 是否开启自动驼峰命名规则映射：从数据库列名到 Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回 map 时 true：当查询数据为空时字段返回为 null，false：查询数据为空时，字段被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的 SQL 打印出来，在开发和测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.shiro.boot: debug
    org.springframework: warn
